# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncalc.proto\"#\n\x14\x63\x61lculateStringInput\x12\x0b\n\x03str\x18\x01 \x01(\t\"\'\n\x15\x63\x61lculateStringOutput\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32P\n\nCalculator\x12\x42\n\x0f\x43\x61lculateString\x12\x15.calculateStringInput\x1a\x16.calculateStringOutput\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CALCULATESTRINGINPUT._serialized_start=14
  _CALCULATESTRINGINPUT._serialized_end=49
  _CALCULATESTRINGOUTPUT._serialized_start=51
  _CALCULATESTRINGOUTPUT._serialized_end=90
  _CALCULATOR._serialized_start=92
  _CALCULATOR._serialized_end=172
# @@protoc_insertion_point(module_scope)
